version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "9000:5000"   # hostPort:containerPort

  frontend:
    build: ./frontend
    ports:
      - "3000:80"     # hostPort:containerPort
